set_property SRC_FILE_INFO {cfile:/home/guille/Documentos/VivadoProj/pwm_gen/pwm_gen.srcs/sources_1/bd/clock_and_adc/ip/clock_and_adc_clk_wiz_0_0/clock_and_adc_clk_wiz_0_0.xdc rfile:../../../pwm_gen.srcs/sources_1/bd/clock_and_adc/ip/clock_and_adc_clk_wiz_0_0/clock_and_adc_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:C1/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/guille/Documentos/VivadoProj/pwm_gen/pwm_gen.srcs/constrs_1/new/const1.xdc rfile:../../../pwm_gen.srcs/constrs_1/new/const1.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.08
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports extclk]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports pwm_out]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports adc_in]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports reset]
