set_property SRC_FILE_INFO {cfile:/home/guille/Documentos/VivadoProj/pwm_gen/pwm_gen.srcs/constrs_1/new/const1.xdc rfile:../../../pwm_gen.srcs/constrs_1/new/const1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports s_out]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports clk]
