set_property PACKAGE_PIN L16 [get_ports extclk]
set_property IOSTANDARD LVTTL [get_ports extclk]
set_property PACKAGE_PIN V12 [get_ports pwm_out]
set_property IOSTANDARD LVTTL [get_ports pwm_out]
set_property PACKAGE_PIN K16 [get_ports adc_in]
set_property IOSTANDARD LVTTL [get_ports adc_in]
set_property PACKAGE_PIN Y16 [get_ports reset]
set_property IOSTANDARD LVTTL [get_ports reset]

set_property DRIVE 24 [get_ports pwm_out]
set_property SLEW FAST [get_ports pwm_out]
