# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const1.xdc

# Block Designs: bd/clock_and_adc/clock_and_adc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_and_adc || ORIG_REF_NAME==clock_and_adc} -quiet] -quiet

# IP: bd/clock_and_adc/ip/clock_and_adc_clk_wiz_0_0/clock_and_adc_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_and_adc_clk_wiz_0_0 || ORIG_REF_NAME==clock_and_adc_clk_wiz_0_0} -quiet] -quiet

# IP: bd/clock_and_adc/ip/clock_and_adc_xadc_wiz_0_0/clock_and_adc_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_and_adc_xadc_wiz_0_0 || ORIG_REF_NAME==clock_and_adc_xadc_wiz_0_0} -quiet] -quiet

# XDC: bd/clock_and_adc/ip/clock_and_adc_clk_wiz_0_0/clock_and_adc_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_and_adc_clk_wiz_0_0 || ORIG_REF_NAME==clock_and_adc_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/clock_and_adc/ip/clock_and_adc_clk_wiz_0_0/clock_and_adc_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_and_adc_clk_wiz_0_0 || ORIG_REF_NAME==clock_and_adc_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/clock_and_adc/ip/clock_and_adc_clk_wiz_0_0/clock_and_adc_clk_wiz_0_0_ooc.xdc

# XDC: bd/clock_and_adc/ip/clock_and_adc_xadc_wiz_0_0/clock_and_adc_xadc_wiz_0_0_ooc.xdc

# XDC: bd/clock_and_adc/ip/clock_and_adc_xadc_wiz_0_0/clock_and_adc_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_and_adc_xadc_wiz_0_0 || ORIG_REF_NAME==clock_and_adc_xadc_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/clock_and_adc/clock_and_adc_ooc.xdc
